MyShop/urls.py
from django.contrib import admin
from . import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('log_auth/', include('log_auth.urls')),
  ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from  django.conf.urls import url
from django.urls import path
from  . import views
from django.conf import settings
from django.conf.urls import static
urlpatterns = [
    path('<int:pk>/', views.AddBookToCartView.as_view(), name='Cart_upd'),
    path('', views.CartView.as_view(), name='view_cart'),
    path('delete_book/<int:pk>', views.DeleteBookCart.as_view(), name='delete_book'),
]

log_auth/urls.py
from django.urls import path
from log_auth.views import *

app_name = 'auth'
urlpatterns = [
    path('login', LogView.as_view(), name='log_in'),
    path('logout', LogOutView.as_view(), name='log_out'),
    path('create-user', CreateUser.as_view(), name='create_user'),
    path('update-user/<int:pk>', UpdateUser.as_view(), name='update_user'),
    path('view-user/<int:pk>', ViewUser.as_view(), name='view_user'),
    path('password-reset', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset-done', PasswordResetView.as_view(), name='password_reset'),
    path('password-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         PasswordResetView.as_view(), name='password_reset_confirm'),
]

log_auth/models.py
from django.db import models

# Create your models here.

log_auth/forms.py
from django import forms
from django.forms import ModelForm
from cart.models import User

class CreateUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

class UpdateUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

log_auth/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth import login, get_user_model
from django.contrib.auth.views import LoginView,LogoutView, PasswordResetView, PasswordResetConfirmView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from cart.models import User
from .forms import CreateUserForm, UpdateUserForm
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import UserPassesTestMixin


class LogView (LoginView):
   template_name = 'log_auth/login.html'

class LogOutView (LogoutView):
   template_name = 'log_auth/logout.html'

class CreateUser(CreateView):
   model = User
   template_name = 'log_auth/create_user.html'
   form_class = CreateUserForm

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['next'] = self.request.GET.get('next', '/')
      return context

   def get_success_url(self):
      self.object.set_password(self.object.password)
      self.object.save()
      return self.request.POST.get('next', '/')


class UpdateUser(UserPassesTestMixin, UpdateView):
   model = User
   template_name = "log_auth/update_user.html"
   form_class = UpdateUserForm

   def get_success_url(self):
      print(self.object)
      return reverse_lazy('view-user', kwargs={'pk': self.object.pk})

   def test_func(self):
      return self.request.user.pk == self.kwargs.get('pk')


class ViewUser(UserPassesTestMixin, DetailView):
   model = User
   template_name = "log_auth/user.html"

   def test_func(self):
      return self.request.user.pk == self.kwargs.get('pk')

class PasswordResetView(PasswordResetView):
   template_name = 'log_auth/password_reset_form.html'
   email_template_name = 'log_auth/password_reset_email.html'
   success_url = '/'

class PasswordResetConfirmView(PasswordResetConfirmView):
   template_name = 'log_auth/password_reset_confirm.html'
   success_url = '/'

log_auth/templates/log_auth/create_user.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>создать пользователя</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Save" class="btn btn-primary">
        <input type="hidden" name="next" value="{{ next }}">
        <input type="button" value="Back" onclick="history.back();" class="btn btn-secondary">
    </form>
</body>
</html>

log_auth/templates/log_auth/login.html
{% extends "base1.html" %}
{% block content %}
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Вход</title>
</head>
<body>
<form method="post" action="{% url 'auth:log_in' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="Вход" class="button">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}" >Lost password?</a></p>

</body>
{% endblock %}

log_auth/templates/log_auth/logout.html
{% extends "base.html" %}

{% block content %}

<p>Logged out!</p>

<a href="{% url 'log_out'%}">Click here to login again.</a>

{% endblock %}

log_auth/templates/log_auth/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset Confirm</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Confirm" class="btn btn-primary">
    </form>
</body>
</html>

log_auth/templates/log_auth/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset Email</title>
</head>
<body>
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
</body>
</html>

log_auth/templates/log_auth/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset Form</title>
</head>
<body>
{% load crispy_forms_tags %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Reset" class="btn btn-primary">
    </form>
</body>
</html>

log_auth/templates/log_auth/update_user.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>пользователь</title>
</head>
<body>
 <div class="container">
        <h2>Здесь вы можете отредактировать свой профиль, {{ object.username }}</h2>
        {% load crispy_forms_tags %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Update" class="btn btn-primary">
            <input type="button" value="Back" onclick="history.back();" class="btn btn-danger">
        </form>
    </div>
</body>
</html>

log_auth/templates/log_auth/user.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>пользователь</title>
</head>
<body>
<div class="container">
 <h2>Ваш профиль</h2>
        <table class="table table-striped">
            <tr>
                <th>Логин</th>
                <td>{{ object.username }}</td>
            </tr>
            <tr>
                <th>Фамиля</th>
                <td>{{ object.first_name }}</td>
            </tr>
            <tr>
                <th>Имя</th>
                <td>{{ object.last_name }}</td>
            </tr>
            <tr>
                <th>E-mail</th>
                <td>{{ object.email }}</td>
            </tr>
        </table>
        <a href="{% url 'auth:update_user' user.pk %}" class="btn btn-primary">Редактировать профиль</a>
    </div>