MyShop/urls.py
from django.contrib import admin
from . import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('log_auth/', include('log_auth.urls')),
  ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from  django.conf.urls import url
from django.urls import path
from  . import views
from django.conf import settings
from django.conf.urls import static
urlpatterns = [
    path('<int:pk>/', views.AddBookToCartView.as_view(), name='Cart_upd'),
    path('', views.CartView.as_view(), name='view_cart'),
    path('delete_book/<int:pk>', views.DeleteBookCart.as_view(), name='delete_book'),
]

log_auth/urls.py
from django.urls import path
from log_auth.views import *

app_name = 'auth'
urlpatterns = [
    path('login', LogView.as_view(), name='log_in'),
    path('logout', LogOutView.as_view(), name='log_out'),
    path('create-user', CreateUser.as_view(), name='create_user'),
    path('update-user/<int:pk>', UpdateUser.as_view(), name='update_user'),
    path('view-user/<int:pk>', ViewUser.as_view(), name='view_user'),
    path('password-reset', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset-done', PasswordResetView.as_view(), name='password_reset'),
    path('password-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         PasswordResetView.as_view(), name='password_reset_confirm'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <style>
* {
  margin: 0;
  padding: 0;
}
html,
body {
  height: 100%;
}
.wrapper {
  display: flex;
  flex-direction: column;
  height: 100%;
}
.content {
  flex: 1 0 auto;
}
.footer {
  flex: 0 0 auto;
}
 </style>
</head>
<body style="color:grey; background-color:lemonchiffon">
<div class="wrapper">
<div class="content">
    {% if user.is_authenticated %}
   {% if perms.books.view_series %}
       <h2 align="center"> Здравствуйте, сотрудник {{ user.username }}</h2>
   {% else %}
     <h2 align="center"> Добро пожаловать, уважаемый {{ user.username }} ! Самые лучшие книги для Вас только в нашем магазине!</h2>
   {% endif %}
   <a href="{% url 'auth:log_out' %}?next={{request.path}}" class="btn btn-secondary" > выйти из личного кабинета </a>
    <a href="{% url 'auth:view_user' user.pk%}" class="btn btn-secondary" > личные данные </a>
     <a href="{% url 'MainList'%}"class="btn btn-warning">Вернуться на главную </button></a> </td>
     <a href="{% url 'view_cart'%}"class="btn btn-info">Перейти в корзину </a>
          {% if perms.books.view_series %}
         <a href="{% url 'order_list_pers'%}"class="btn btn-info">Перейти к заказам покупателей </a>
          {% else %}
          <a href="{% url 'order_list_cust'%}"class="btn btn-info">Перейти к заказам </a>
          {% endif %}
     {% else %}
     <h2 align="center"> Добро пожаловать, покупатель ! Самые лучшие книги для Вас только в нашем магазине!</h2>
       <p> Перейдите по ссылке и для входа в личный кабинет или пройдите регистрацию</p>
   <a href="{% url 'auth:log_in' %}?next={{request.path}}" class="btn btn-secondary"> Войти </a>
    <a href="{% url 'auth:create_user' %}?next={% url  "MainList" %}" class="btn btn-secondary" >Регистрация</a>
         <a href="{% url 'MainList'%}"class="btn btn-warning">Вернуться на главную </button></a> </td>
     <a href="{% url 'view_cart'%}"class="btn btn-info">Перейти в корзину </a>
          <a href="{% url 'order_list_cust'%}"class="btn btn-info">Перейти к заказам </a>
    {% endif %}
    {% block content %}{% endblock %}
   </div>
   <div class="footer">
    {% block footer %}
     <h6 class="nav justify-content-center"> Спасибо, что посетили наш сайт!</h6>
     <h6 class="nav justify-content-center"> © Copyright 2019 Vitaly Kulinkovich</h6>
    {% endblock %}
   </div>
 </div>
</body>
</html>

templates/base1.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <style>

 </style>
</head>
<body style="color:grey; background-color:lemonchiffon">

        <h2 align="center"> Пожалуйста, введите свой логин и пароль</h2>
    {% block content %}{% endblock %}
   </div>
   <div class="footer">
    {% block footer %}
     <h6 class="nav justify-content-center"> Спасибо!</h6>
    {% endblock %}
</body>
</html>